# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='date_up_area',
            field=models.DateField(auto_now_add=True),
        ),
    ]
