# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20160208_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='date_up_area',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
