# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20160208_1159'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
    ]
