# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0006_auto_20160208_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korp_house', models.CharField(max_length=4)),
                ('date_create_house', models.DateTimeField(auto_now_add=True)),
                ('street_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Street')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'house',
            },
        ),
    ]
