# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='num_house',
            field=models.IntegerField(default=1),
        ),
    ]
