# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20160208_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'DOma'},
        ),
    ]
