# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_auto_20160208_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name_area',
            field=models.CharField(max_length=200, verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
    ]
