# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_auto_20160209_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name_area',
            field=models.CharField(max_length=200, verbose_name='\u0420\u0430\u0439\u043e\u043d \u0433\u043e\u0440\u043e\u0434\u0430'),
        ),
    ]
