# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_auto_20160209_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='name_street',
            field=models.CharField(default='\u0443\u043b.', max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0443\u043b\u0438\u0446\u044b'),
        ),
    ]
