# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_auto_20160209_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='korp_house',
            field=models.CharField(blank=True, max_length=4, verbose_name='\u041a\u043e\u0440\u043f\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='house',
            name='num_house',
            field=models.IntegerField(default=1, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0434\u043e\u043c\u0430'),
        ),
    ]
