# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_auto_20160209_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '\u0420\u0430\u0439\u043e\u043d \u0433\u043e\u0440\u043e\u0434\u0430 ', 'verbose_name_plural': '\u0420\u0430\u0439\u043e\u043d\u044b \u0433\u043e\u0440\u043e\u0434\u0430'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': '\u0414\u043e\u043c', 'verbose_name_plural': '\u0414\u043e\u043c\u0430'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': '\u0423\u043b\u0438\u0446\u0430', 'verbose_name_plural': '\u0423\u043b\u0438\u0446\u044b'},
        ),
    ]
