# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='ip_switch',
            field=models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP \u0430\u0434\u0440\u0435\u0441'),
        ),
    ]
