# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_switch_switch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='switch_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u043d\u0430 \u0441\u0435\u0442\u0438'),
        ),
    ]
