# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_delete_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_switch', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'switch',
                'verbose_name': '\u041a\u043e\u043c\u043c\u0443\u0442\u0430\u0442\u043e\u0440',
                'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0443\u0442\u0430\u0442\u043e\u0440\u044b',
            },
        ),
    ]
