# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0024_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='ipaddr_switch',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='name_switch',
            field=models.CharField(max_length=100, verbose_name='\u041e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u043d\u0430 \u0441\u0435\u0442\u0438'),
        ),
    ]
