# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0025_auto_20160209_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='switch_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.House'),
        ),
        migrations.AddField(
            model_name='switch',
            name='switch_modelid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.SwitchModel'),
        ),
    ]
