# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0027_auto_20160209_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='pd_switch',
            field=models.CharField(default='\u043f\u0434.', max_length=100, null=True),
        ),
    ]
