# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0029_auto_20160209_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchmodel',
            name='num_ports_model',
            field=models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043f\u043e\u0440\u0442\u043e\u0432'),
        ),
    ]
