# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0030_auto_20160209_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.CharField(max_length=5, verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430')),
                ('pd', models.CharField(max_length=5, verbose_name='\u041f\u043e\u0434\u044a\u0435\u0437\u0434')),
                ('port', models.IntegerField(verbose_name='\u041f\u043e\u0440\u0442')),
                ('FIO', models.CharField(max_length=100, verbose_name='\u0424\u0418\u041e')),
                ('date_create_descr', models.DateTimeField(auto_now_add=True, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Switch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'description',
                'verbose_name': '\u0414\u0435\u0441\u043a\u0440\u0438\u043f\u0448\u0435\u043d',
                'verbose_name_plural': '\u0414\u0435\u0441\u043a\u0440\u0438\u043f\u0448\u0435\u043d\u044b',
            },
        ),
    ]
