# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='FIO',
            new_name='descr_FIO',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='kv',
            new_name='descr_kv',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='pd',
            new_name='descr_pd',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='port',
            new_name='descr_port',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='switch',
            new_name='descr_switch',
        ),
    ]
